kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.2.86
        k3s-1:
          ansible_host: 192.168.2.77
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.2.87
