kind: Secret
ansible_user: ENC[AES256_GCM,data:acdNgR5NMJ4=,iv:Gah+YA0p0OTMygbUbQSVKERuR9g5wtPt708P2NyL6VI=,tag:+r5pzudlqh14lqxtj4Vnpw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UHQXHEgP,iv:M8fBvmdl0KWhE/Yk1Ssnu/mIbd7DDk43qgoriJJyvcQ=,tag:2yBHZrbp6dDxc8qHO8JZAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-23T01:29:44Z"
    mac: ENC[AES256_GCM,data:ISbxaq1adVWFHABhctcJBwRuG0PZW+2lQPfsnhRob2F1pWKGdj36E5wtdBJjkge5pbU4DwIqiUqDWbh8WqiyY2KUo36JqskxJowi40YLojuzbCDL4uMsWze1CnmD4ykiyG/H2K0euGJJleQyPiEc6CSqxOW6td6cZsBPHwWmBeU=,iv:syXky3ZI+oPdGFYGbMrXrE1RNt8tM5+fK1gkhD4n/tA=,tag:iHIDscnUeaswsqXdyvi4Ug==,type:str]
    pgp:
        - created_at: "2021-10-23T01:29:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9ce7oIX8WL2ARAAnKGZegnlAhyj6TecFQgTRIk4V+gkWZHQDAFOTSB7y6af
            8p8pGLSae+ARsK5C4mVy6jgw70OVbRa56zi4DI6TEP+1mBz2rTbIv0pSTOOVKpl6
            FPQgS470CWxNHibjfzybXC5DPlxYQe0TW55/H2aFM1Gya39UO2RL3QGCJZmbMMaJ
            hmgG9/y6AZwVY/wouHJMJHOYTu6Boh1hksamQ1Bm8YRMj5y4HsFyqWoS1aW6Gvgr
            fmLFaaRPJ1MWZSOrgk2+U+PzSdnb8SW4f4FLUhuejLDKM66R4/8H6IeAGU1/VJ7h
            w9WUhV3cVctqCMhjr+O6kZXxYJfDv7HSivPPIY/0CP8aiXy520m2IOQQ9X42WX4h
            ax9QDYZbd1kBzKvvSa5EzjBs20Zdq7yKPIFRThwaBevQSYdfBCNoOpIyeRs60bna
            Q4v9UvV+KZPVcrrjlo+Judwjk6ks9egNYR0fBdPJZmV0OAffJIOISz2huvXoK2pK
            eWV1S3+w7fYXGRsQAtMUYMqvMP+f7BbYx9OtjzYmKxv4TsrmQTwiv3LJ88QxSw9M
            TcMj7Wjh9dVlNEgFMRWStIl+4yDQWUzgx9BY3RE2GWTqph/FYrWVKG+CZ+3jzhIC
            L0S0JfdyMHO5bWo1v7wpCYsKCCBKzSNPOd1XZrW/zwSENJXmN8axR013a6r+W+jU
            aAEJAhWHc9eX7dfBeIIJ3N8wjM2+L1NOJB+Gj53JthlpEs1DPKi9mGzl9IL2AK9Y
            0a0HO+jxqJ7O+flrhuQMka/78MuEDMhGbbIfsSHw0tlN1UUC+Z+BGreDLaw/Ec3C
            FcDBUCUrdeon
            =h2/o
            -----END PGP MESSAGE-----
          fp: 28FAE7DBB9F187A6D1956F6150163F0A471743F3
    unencrypted_regex: ^(kind)$
    version: 3.7.1
